"""new user table

Revision ID: 40943014ddeb
Revises: d2de6550783e
Create Date: 2020-10-29 10:00:24.707999

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '40943014ddeb'
down_revision = 'd2de6550783e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=False))
    op.add_column('users', sa.Column('fullname', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('password', sqlalchemy_utils.types.password.PasswordType(max_length=1137), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'password')
    op.drop_column('users', 'last_updated')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'fullname')
    op.drop_column('users', 'email')
    op.drop_column('users', 'created')
    # ### end Alembic commands ###
