"""Edited user

Revision ID: 433fa82ceb99
Revises: 428e133612ee
Create Date: 2020-11-09 10:00:29.941863

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '433fa82ceb99'
down_revision = '428e133612ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    # ### end Alembic commands ###
