"""create login log

Revision ID: b1b08eb52852
Revises: b8803837ee09
Create Date: 2020-10-29 12:50:21.045691

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision = 'b1b08eb52852'
down_revision = 'b8803837ee09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
