"""created models

Revision ID: b4ce56caeead
Revises: 9077c40d9494
Create Date: 2020-10-30 11:33:48.190400

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision = 'b4ce56caeead'
down_revision = '9077c40d9494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
