"""create login log

Revision ID: b8803837ee09
Revises: 40943014ddeb
Create Date: 2020-10-29 12:47:33.804768

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision = 'b8803837ee09'
down_revision = '40943014ddeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
