"""create login log

Revision ID: dc0e4a4d2015
Revises: b1b08eb52852
Create Date: 2020-10-29 12:52:12.050653

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision = 'dc0e4a4d2015'
down_revision = 'b1b08eb52852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('login_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('grant_type', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sqlalchemy_utils.types.ip_address.IPAddressType(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_logs')
    # ### end Alembic commands ###
