version: "3"

services:
  app:
    build:
      context: ../../
      dockerfile: docker-develop.dockerfile
    container_name: fastapi-develop
    environment: 
      - POSTGRES_SERVER=localhost
    env_file: ../../develop.env
    ports:
      - 80:80
    depends_on:
      - database
    network_mode: "host"
  
  database:
    image: "postgres:latest"
    container_name: database-pg
    restart: always
    ports:
      - 5432:5432
    env_file: ../../develop.env
    volumes:
      - pgsql_volume:/var/lib/postgresql/data
    network_mode: "host"
  
volumes:
  pgsql_volume: